### ISSUE TITLE
File Browser for RFID-assignments 

### ISSUE THREAD

**Issue by mariolukas** [biologist79/Tonuino-ESP32-I2S#10]
Just want to let you know that i am working on a File Browser for making RFID-assignments more convenient.

There will be a json file on the SD-Card which contains the current file tree of the SD-Card. The file is created by a function in the backend code. This function can be called by a websocket request.The request can be sent by clicking the link below the file Browser box.

The file is loaded by an ajax call. I am using [jsTree](https://www.jstree.com/) for creating the dom.

I made it this way, because i wanted to prevent long blocking times for example in the setup() routine.  The refresh link can be called after new files were copied to the SD-Card.

![filebrowser](https://user-images.githubusercontent.com/1033122/100514539-d9cda600-3175-11eb-87a2-7ca8d88e1f70.gif)

I will do a pull request when it's done. I am still struggling with the json formating.

**Comment by biologist79** [comment]
Wow, that is really really cool! Indeed my initial plan was EXACTLY the same (*) but I had so much work with all that other stuff.  And finally, to be honest, Js is not my world 👍 So I really appreciate your plan/work. The way to use a pre-formatted json makes absolutely sense. Just tell me if you need support (apart of Js, hehe).

(*) Indeed I had some out-commented code that was used for parsing (maybe you recognized). However, I removed it a few days back as I thought this feature will never be released :-D

**Comment by biologist79** [comment]
BTW: Can't wait to see this running on my Tonuinos! :-D

**Comment by mariolukas** [comment]
It is almost finished. I will do some final tests and finally do a pull request.   

<img width="358" alt="Bildschirmfoto 2020-11-30 um 10 49 39" src="https://user-images.githubusercontent.com/1033122/100608662-036d0580-330d-11eb-99f4-207723fd4d57.png">

**Comment by biologist79** [comment]
Cool!
A second thing: When doing RFID-linking, a green box opens to indicate a successful operation. I'd like to automatically dismiss this box after a few seconds (3s or so). Tried around a bit but in the end it didn't work. I was able to automatically dismiss it but after that it was dismissed it never appeared again for RFID-linkings done subsequently. Guess it's not a big thing; maybe you know how to do that.

**Comment by mariolukas** [comment]
What do  you think about using [toastr](http://plnkr.co/edit/6W9URNyyp2ItO4aUWzBB?p=preview) messages for indicating successful operations, warning,  errors etc.
I am  already testing the file browser indications using toasts.

<img width="358" alt="Bildschirmfoto 2020-11-30 um 10 49 39" src="https://user-images.githubusercontent.com/1033122/100636079-991a8c00-3331-11eb-95cc-f2e9a8c8e5bd.png">

**Comment by biologist79** [comment]
In German I'd say: "Ich bin da emotionslos" :-) So: I'm fine with it.
Personally I just make sure to use my own server-infrastructure (for link-hrefs) in order to avoid monitoring/tracking by Google & Co.

**Comment by mariolukas** [comment]
> In German I'd say: "Ich bin da emotionslos" :-) So: I'm fine with it.

Passt. 

> Personally I just make sure to use my own server-infrastructure (for link-hrefs) in order to avoid monitoring/tracking by Google & Co.
So you just need to copy the needed libs to your server and replace the links by your own.

**Comment by biologist79** [comment]
Yes, I know. I also did this in the past for bootstrap and jQuery as well.
However, had a look at https://codeseven.github.io/toastr/demo.html and looks really good I have to admit. So I'm really looking forward to your pull request :-)

**Comment by mariolukas** [comment]
feature/filebrowser #12 
I tried two times to create a pull request which  contains only the file browser changes. I merged with the upstream master before i created the pull request, maybe that is the reason why so many changes are applied. Not the best way to understand what i changed. The additions to the main.cpp are mainly new functions for the file index handling and json writing, some websocket event handling stuff and a static route for delivering the files.json. 
I am using anther esp32 board, that is the reason why i changed platformio.ini (but added a platformio.ini.default file). I would appreciate moving all the config/defines to an extra file like config.h or something similar. I think that makes it easier for us all to handle custom pinouts without messing up the code with every pull request. I still have some additional ideas but will open new issues for those :)

**Comment by biologist79** [comment]
Definitely outsourcing stuff makes totally sense; 100% ACK! Will be one of the next things I'll change.
Now I don't know how to merge all that stuff to my code to be honest because the left files in the diff are not my current master. Wouldn't be a problem to do it manually as I know where to look, but then the info is gone that you're the contributor. Hmm.

**Comment by mariolukas** [comment]
I will give it a try with a fresh fork. I think that would be the easiest way for both of us.

**Comment by biologist79** [comment]
Couldn't wait and c&p mgmt-html-File and flashed it onto my Lolin32. As I don't have an json-file on the SD-card, the GUI keeps "loading". However, every 10-15s (or so) a msg appears "Aktion erfolgreich ausgeführt" even if I don't do anything.
Addtionaly you stated "margin-botton" in the html-head instead of "margin-bottom". 

Haha, that's a new experience for me to assign bugs to anybody else in my own project :-D However, big thanks for your contribution!

**Comment by mariolukas** [comment]
> Couldn't wait and c&p mgmt-html-File and flashed it onto my Lolin32. As I don't have an json-file on the SD-card, the GUI keeps "loading". However, every 10-15s (or so) a msg appears "Aktion erfolgreich ausgeführt" even if I don't do anything.

Yes the spinner is running, cause it tries to load a file. I think this is caused by the tree library. I will try to catch the 404 error message. See comments in pull request (todo). 

First time you need to hit the refresh icon below the box for initial index file creation. This might take some time, depending on how many files are on your card.  

"Aktion erfolgreich ausgeführt" 
Something what i also discovered. But this is related to the ping/pong event.  I was too lazy to have a closer look to the websocket routine where the "ok" event is triggered. But it seems to be triggered every time when a pong is received. You can discover that on the js console. I think this behaviour was not visible before, cause the old notification was more a static approach. 

> Addtionaly you stated "margin-botton" in the html-head instead of "margin-bottom".

Thanks.

> 
> Haha, that's a new experience for me to assign bugs to anybody else in my own project :-D However, big thanks for your contribution!

So you finally managed merging this?

**Comment by biologist79** [comment]
Clicking the refresh-button would not have been leading to a solution as I (really) only did c&p with the html-file. So no server-support.
So: no, didn't manage the merge. I'm not super-familiar with git, so would have to point out. However, doing it manually would not be a problem, but then nobody knows it was your contribution. Ehre, wem Ehre gebührt :-)

**Comment by mariolukas** [comment]
Don't worry. I will try to fix that merging mess and will do another pull request.

**Comment by mariolukas** [comment]
I think i managed the merging problem. But i will fix some minor bugs before i will do the pull request. The following todos are open: 

- notification when no file list is available
- more stateful nofitications during file indexing, this can take a long time depending on the number of files

**Comment by biologist79** [comment]
Looks good, thank you!
Will try this tonight I guess.

**Comment by biologist79** [comment]
Hmm, created a new branch, did a pull-request by myself and synct it locally to a branch. Ok so far but it's about time to gain knowledge on git :->
However, did some small changes in platformio.ini, compiled and flashed the stuff. Tonuino + GUI is working, but GUI doesn't interact with Tonuino (even ping/pong) etc. Have to point out what's wrong. Firefox' debugger told me that a .js-File was not downloadable from my server (which is crap; it works, I tested it manually).

Will have a look later.

**Comment by mariolukas** [comment]
Maybe there are still hard coded ip addresses in the html, which i added for debugging. I managed to make it conditional in the current version which is still not commited.

Give me some time. This branch was even not final. I did a lot of additional work on it which was still not commited and pushed to GitHub. I will push the latest changes tonight. I am not even sure if there is a need for the ping/pong stuff by using websockets. The websocket connection is hold on until it will be actively closed by the browser or by the tonuino (what also happens when it runs into a timeout).

Anyway I started working on this issue because i am having a problem when the file indexing function is called. Indexing works like a charm, but it blocks the websocket process from sending ping/pongs, what leads to a lot of messages in the frontend, even if the websocket connection is still alive, cause the (ping/pong) timer in JavaScript is doing its job well :)

 I already tried to add a couple of watchdog timer resets during the recursion while file indexing. But without success. This keeps the watchdog running but the websocket task is still blocked. In addition to all that i also tried making a task on the second cpu of all the filebrowser stuff, without any luck so far.

**Comment by biologist79** [comment]
Ok, take your time 👍 
It's only in my devel-branch so there's no need to rush.

**Comment by mariolukas** [comment]
Maybe i am not able to fix this socket issue by myself. It is really hard to debug and i already looked over most of the issues on asyncWebServer library. I hope i will find a solution.

**Comment by biologist79** [comment]
Commit what's working and I'll see what I can do.

**Comment by biologist79** [comment]
Regarding task-stuff: did you have a look at my tasks? I used vTaskDelay() along with esp_task_wdt_reset(). For example if the music stops, it has to be called as the loop runs too fast without yield(). But indeed, that's not so easy - I also spent a lot of time to get it running as it's (in my opinion) not very well documented. I've been missing something like a "guideline for task-programmers", hehe.

**Comment by biologist79** [comment]
Wasn't aware you already commited. However, had I look at your repository and merged it into my devel-branch + tested it. Is really looking and working great! So finally, have you been successful in using vTaskDelay() or are there still problems ongoing? However, I didn't notice reboots while creating the json-file. The only thing I noticed was like it took three times or so to create the json-file when starting for the first time. However, not a big thing. Guess will have a look at it this evening.

Like it! Especially learning RFIDs via cellphone is nice!

**Comment by mariolukas** [comment]
I added my latest changes a couple of minutes ago: 
https://github.com/mariolukas/Tonuino-ESP32-I2S/tree/feature/sdbrowser

Indeed i managed to fix the issue with the blocking stuff. However as you discovered we have one thing left open. We need to find a solution to prevent multiple task creation when the indexing task is already running. The task is not like the others, it does not run in  a loop. It runs and terminates itself after execution. And that is exactly the point where we need to add a mutex or semaphore, to prevent multiple task execution.

https://github.com/mariolukas/Tonuino-ESP32-I2S/blob/f940a2ee6736eb70526cb1798cded4c7f2d7fc91/src/main.cpp#L3309

**Comment by mariolukas** [comment]
I think this is finally done.
