### ISSUE TITLE
gerber files for D32 missing outline

### ISSUE THREAD

**Issue by michi1g** [biologist79/Tonuino-ESP32-I2S#31]
I tried to order your PCBs form jlcpcb as you suggested but after review they sent me an email:
```
Audit Failed
Failure Reason:
1.Hi Sir/ Madam, there is no board outline in your file, please kindly check it!
```
Can your recheck the board?

**Comment by biologist79** [comment]
Hi,

sorry. I revised the PCB. Please try again.

Greets.

**Comment by michi1g** [comment]
Thx for the fast help. I reuploaded and will close the issue if it passes

**Comment by michi1g** [comment]
Unfortunately still getting the same error from jlcpcb

**Comment by biologist79** [comment]
Hmm. Omitted dimensioning this time. Maybe now?
Sorry...

**Comment by biologist79** [comment]
So? Working now?

**Comment by biologist79** [comment]
As it turned out it was still missing. Outline was on wrong layer; sorry!
However, should be fixed now (finally!).
