### ISSUE TITLE
Uploaded files via FTP are always empty

### ISSUE THREAD

**Issue by weitzj** [biologist79/Tonuino-ESP32-I2S#36]
I have tries to upload files via the Linux `ftp` command or via filezilla with a single connection and `passive` disabled.
But the files are just `touched` on the SD-card, but no content is written to the file.

Do you have any tips, what I am doing wrong?

**Comment by weitzj** [comment]
Ah. I think i am getting closer:

```bash

# open ftp client
ftp

# connect to your Tonuino
# username, password are esp32
open 192.168.178.73


# enable passive mode
passive

# send a file 
send myfile.mp3 

```

**Comment by weitzj** [comment]
The working setup. Filezilla with 1 connection in passive mode:

![image](https://user-images.githubusercontent.com/829277/102776945-eec1e180-438f-11eb-9178-d1d6b6401678.png)

![image](https://user-images.githubusercontent.com/829277/102776997-05683880-4390-11eb-9757-0e059c7274e4.png)

**Comment by weitzj** [comment]
Thank you for this great project :heart:

**Comment by biologist79** [comment]
What I can add from my perspektive: I had issues where FTP-transfer seemed to take place (round about twice as fast as usual), but in the end file's size was 0. I guess this was due to bad wire-connection(s) on the breadboard.
