### ISSUE TITLE
MQTT doesn't work

### ISSUE THREAD

**Issue by erniberni** [biologist79/Tonuino-ESP32-I2S#47]
I enabled MQTT with IP, user and password. 
On serial I see the correct credentials from NVS.  
In the mosquitto log I don't see anything from the client, no connection trials.

**Comment by biologist79** [comment]
Please provide serial-log-output.
I'm using MQTT with my children's Tonuinos every day and I'm surprised to hear there's a problem.
Have you been trying to subscribe to the topics used with mqtt.fx?

**Comment by erniberni** [comment]
Time to give you a big thumbs up. Really great project.

**Comment by biologist79** [comment]
Fixed with the last commit!
Already had this point in my mind but had no way that I really liked.
Please test.

**Comment by erniberni** [comment]
Tested and approved !
