### ISSUE TITLE
FTP Upload Probleme

### ISSUE THREAD

**Issue by erniberni** [biologist79/Tonuino-ESP32-I2S#57]
Hallo,
es gelingt mir nicht, mehrere Files oder ganze Verzeichnisse per ftp zu übertragen. Einzelne Files nacheinander klappt.
Ich nutze FileZilla auf Ubuntu, nur damit ist es mir gelungen überhaupt eine ftp-Verbindung vernünftig aufzubauen, da man TLS gezielt ausschalten/verhindern muss.
LG Reinhard

**Comment by biologist79** [comment]
Also in zwei Sprachen braucht's Bug-Reports nicht...
